AI4Bharat/Chitralekha-Frontend

src/containers/Organization/Video/VideoLanding.jsx
1. Updating time spent only when tab is active
2. Saving and Updating time when tab or browser window is closed
=> not invoking time spent api when tab is inactive

src/containers/Organization/Video/RightPanel.jsx
Added delay for close snackbar for save transcript
=> fix for snackbar closing immediately for transcription task

src/containers/Organization/Project/TaskList.jsx, src/redux/actions/api/Project/ReopenTask.js
2 files updated: Project/TaskList.js and Project/ReopenTask.js
=> added delete voiceover and reopen task feature

src/containers/Organization/Video/components/SubtitleBoxes.jsx
Issue in reading starttime of previou, for first subtitle in timeline is resolved
=> fixed issue while dragging first subtitle card in bottom timeline

src/containers/Organization/Video/components/Metronome.jsx, src/containers/Organization/Video/components/SubtitleBoxes.jsx
2 files changed: metronome.js and SubtitleBoxes.jsx
feature to stop allowing: dragging of all voiceover subtitle boxes
and also to stop allowing: adding new subtitle box in voiceover timeline
=> added feature to not allow voiceover time change and new subtitle box

src/common/DeleteDialog.jsx, src/common/TaskReopenDialog.jsx, src/common/index.js, src/config/tableColumns.js, src/containers/Organization/Project/TaskList.jsx
Added modal similar to delete dialog for task reopen.
=> added modal for task reopen if voiceover dependency present

src/config/tableColumns.js, src/containers/Organization/Video/RightPanel.jsx
2 files changed: Video/RightPanel.jsx and config/tableColumns.js
Integrated bad sentences model display on transcription complete and added additional column 'Issue Type' in table.
=> display bad sentances on transcription complete

src/containers/Organization/Video/components/SubtitleBoxes.jsx
resolved the issue of last card attaching to the mouse click event and
also fixed issue of 2nd card trying to edit first card.
=> cl-575 fix for last subtitle holding on to the mouse click issue

src/containers/Organization/OrgLevelTaskList.jsx, src/containers/Organization/Project/TaskList.jsx
Added the missed edge case condition upon onViewColumnsChange trigger.
=> fixed the issue of checked column getting dissappeared until page refresh

src/common/ExportDialog.jsx, src/containers/Organization/OrgLevelTaskList.jsx, src/containers/Organization/Project/TaskList.jsx
Reverts AI4Bharat/Chitralekha-Frontend#639
=> Chitralekha 

src/containers/Organization/OrgLevelTaskList.jsx, src/containers/Organization/Project/TaskList.jsx
Reverts AI4Bharat/Chitralekha-Frontend#626
=> Revert "enabled multi transcript task export through checkbox"

src/common/FindAndReplace.jsx, src/containers/Organization/Video/components/SettingsButtonComponent.jsx
Reverts AI4Bharat/Chitralekha-Frontend#659
=> Revert "added fulldata to find and replace"

src/containers/Organization/Video/components/SettingsButtonComponent.jsx
Reverts AI4Bharat/Chitralekha-Frontend#667
=> Revert "enable merge button for VO-TR ui"

package-lock.json, package.json, src/containers/Organization/Video/RightPanel.jsx, src/containers/Organization/Video/TranslationRightPanel.jsx, src/containers/Organization/Video/VideoLanding.jsx, src/containers/Organization/Video/VoiceOverRightPanel1.jsx, src/containers/Organization/Video/audioPanel.jsx
Reverts AI4Bharat/Chitralekha-Frontend#676
=> Revert "Revert "changed audio player""

src/containers/Organization/Video/components/SettingsButtonComponent.jsx
Reverts AI4Bharat/Chitralekha-Frontend#682
=> Revert "added split and regenerate all segments button"

src/containers/Organization/Video/components/SettingsButtonComponent.jsx
Reverts AI4Bharat/Chitralekha-Frontend#683
=> Revert "Revert "added split and regenerate all segments button""

src/common/FindAndReplace.jsx, src/containers/Organization/Video/components/SettingsButtonComponent.jsx
Reverts AI4Bharat/Chitralekha-Frontend#689
=> Revert "Replace all btn fix"

src/common/FindAndReplace.jsx, src/containers/Organization/Video/components/SettingsButtonComponent.jsx
Reverts AI4Bharat/Chitralekha-Frontend#697
=> Revert "Revert "Replace all btn fix""

src/hooks/useAutoSave.js, src/hooks/useUpdateTimeSpent.js, src/redux/actions/apitransport/apitransportUts.js, src/redux/actions/index.js
Reverts AI4Bharat/Chitralekha-Frontend#745
=> Revert "Revert "disable autosave when any other save call is in progress""

src/containers/Organization/Video/components/VideoPanel.jsx
Reverts AI4Bharat/Chitralekha-Frontend#773
=> Revert "enable youtube video if yt-dlp fails"

src/containers/Organization/Project/Project.jsx
Reverts AI4Bharat/Chitralekha-Frontend#779
=> Revert "Restricted members tab visibility in project tab"

src/config/tableColumns.js, src/containers/Organization/TaskQueueStatus/QueueStatusTable.jsx, src/containers/Organization/TaskQueueStatus/TaskQueueStatus.jsx
Reverts AI4Bharat/Chitralekha-Frontend#835
=> Revert "add votr tab in task queue status"

src/config/tableColumns.js, src/containers/Organization/TaskQueueStatus/QueueStatusTable.jsx, src/containers/Organization/TaskQueueStatus/TaskQueueStatus.jsx
Reverts AI4Bharat/Chitralekha-Frontend#836
=> Revert "Revert "add votr tab in task queue status""

src/containers/Organization/OrgLevelTaskList.jsx, src/containers/Organization/Project/TaskList.jsx, src/containers/Organization/Video/VoiceOverRightPanel1.jsx, src/utils/subtitleUtils.js
Reverts AI4Bharat/Chitralekha-Frontend#857
=> Revert "changes for export filename"
